"""Regenerate resources/core/manifest.json from the Python files on disk.

bridge.js fetches this manifest at boot to know which kernel files to copy into
the Pyodide file system (D-010). Run it after adding, renaming or deleting any
file under resources/core/, resources/core/apps/ or resources/core/commands/:

    python3 tools/gen_manifest.py          # write the file
    python3 tools/gen_manifest.py --check  # exit 1 if the file is stale

tests/structure.js runs the same comparison under Node.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "resources" / "core"
MANIFEST = CORE / "manifest.json"


def modules(directory: Path) -> list[str]:
    """Module names (no .py) in a directory, excluding dunder files, sorted."""
    return sorted(
        p.stem for p in directory.glob("*.py") if not p.name.startswith("__")
    )


def build() -> dict:
    return {
        "_comment": "Generated by tools/gen_manifest.py from resources/core/. Do not edit by hand.",
        "core": modules(CORE),
        "apps": modules(CORE / "apps"),
        "commands": modules(CORE / "commands"),
    }


def main(argv: list[str]) -> int:
    fresh = build()
    text = json.dumps(fresh, indent=2) + "\n"
    if "--check" in argv:
        current = MANIFEST.read_text() if MANIFEST.exists() else ""
        if current == text:
            print(f"{MANIFEST.relative_to(ROOT)} is up to date "
                  f"({len(fresh['core'])} core, {len(fresh['apps'])} apps, {len(fresh['commands'])} commands)")
            return 0
        print(f"{MANIFEST.relative_to(ROOT)} is stale; run: python3 tools/gen_manifest.py", file=sys.stderr)
        return 1
    MANIFEST.write_text(text)
    print(f"wrote {MANIFEST.relative_to(ROOT)}: "
          f"{len(fresh['core'])} core, {len(fresh['apps'])} apps, {len(fresh['commands'])} commands")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
